# Generated by Django 5.1.7 on 2025-03-26 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='film/')),
                ('title', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('genre', models.CharField(choices=[('horror', 'horror'), ('comedy', 'comedy')], max_length=100)),
                ('description', models.TextField()),
                ('trailer', models.URLField()),
            ],
        ),
    ]
